services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Markocupic\RotateImage\:
        resource: ../src/
        exclude:
            - ../src/ContaoManager
            - ../src/DependencyInjection
            - ../src/Exception
            - ../src/MarkocupicRotateImage.php
