<?php
/**
 * TL_ROOT/system/modules/rotate_image/languages/de/tl_files.php 
 * 
 * Contao extension: rotate_image 1.0.0 
 * German translation file 
 * 
 * Copyright : &copy; 2015 Marko Cuipc 
 * License   :  
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_files']['rotateImage']['0'] = "Bild um 90° drehen.";
$GLOBALS['TL_LANG']['tl_files']['rotateImage']['1'] = "Bild um 90° drehen.";
 
?>
